#!/bin/sh
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt10to15 $1
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt15to30 $1
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt30to50 $1
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt50to80 $1
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt80to120 $1
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt120to170 $1
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt170to300 $1
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt300to470 $1
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt470to600 $1
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt600to800 $1
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt800to1000 $1
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt1000to1400 $1
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt1400to1800 $1
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt1800to2400 $1
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt2400to3200 $1
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt3200toInf $1
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt15to20_Mu5 $1
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt20to30_Mu5 $1
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt30to50_Mu5 $1
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt50to80_Mu5 $1
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt80to120_Mu5 $1
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt120to170_Mu5 $1
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt170to300_Mu5 $1
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt300to470_Mu5 $1
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt470to600_Mu5 $1
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt600to800_Mu5 $1
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt800to1000_Mu5 $1
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt1000toInf_Mu5 $1
python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt15to20_Mu5 $1
python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt20to30_Mu5 $1
python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt50to80_Mu5 $1
python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt80to120_Mu5 $1
python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt120to170_Mu5 $1
python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt170to300_Mu5 $1
python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt300to470_Mu5 $1
python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt470to600_Mu5 $1
python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt600to800_Mu5 $1
python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt800to1000_Mu5 $1
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt1000toInf_Mu5 $1
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt15to20_EMEnriched $1
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt20to30_EMEnriched $1
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt30to50_EMEnriched $1
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt50to80_EMEnriched $1
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt80to120_EMEnriched $1
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt120to170_EMEnriched $1
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt170to300_EMEnriched $1
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt300toInf_EMEnriched $1
python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt15to20_EMEnriched $1
python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt20to30_EMEnriched $1
python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt30to50_EMEnriched $1
python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt50to80_EMEnriched $1
python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt80to120_EMEnriched $1
python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt120to170_EMEnriched $1
python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt170to300_EMEnriched $1
python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt300toInf_EMEnriched $1
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt_15to20_bcToE $1
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt_20to30_bcToE $1
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt_30to80_bcToE $1
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt_80to170_bcToE $1
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt_170to250_bcToE $1
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_Pt_250toInf_bcToE $1
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_HT100to200 $1
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_HT200to300 $1
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_HT300to500 $1
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_HT500to700 $1
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_HT700to1000 $1
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_HT1000to1500 $1
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_HT1500to2000 $1
#python cmgPostProcessing.py --skim=dilep  --samples=QCD_HT2000toInf $1
