python NMinus1Plots.py --channel=mu --plot=miniReliso &
python NMinus1Plots.py --channel=mu --plot=dxy &
python NMinus1Plots.py --channel=mu --plot=dz &
python NMinus1Plots.py --channel=mu --plot=ip3d &
python NMinus1Plots.py --channel=mu --plot=sip3d &
python NMinus1Plots.py --channel=mu --plot=relIso03 &
python NMinus1Plots.py --channel=mu --plot=relIso04 &
python NMinus1Plots.py --channel=mu --plot=jetPtRatiov1 &
python NMinus1Plots.py --channel=mu --plot=jetPtRelv1 &
python NMinus1Plots.py --channel=mu --plot=jetPtRelv2 &
python NMinus1Plots.py --channel=mu --plot=jetPtRatiov2 &
python NMinus1Plots.py --channel=mu --plot=jetBTagCSV &
python NMinus1Plots.py --channel=mu --plot=jetDR &
#python NMinus1Plots.py --channel=ele --plot=miniReliso &
#python NMinus1Plots.py --channel=ele --plot=dxy &
#python NMinus1Plots.py --channel=ele --plot=dz &
#python NMinus1Plots.py --channel=ele --plot=ip3d &
#python NMinus1Plots.py --channel=ele --plot=sip3d &
#python NMinus1Plots.py --channel=ele --plot=convVeto &
#python NMinus1Plots.py --channel=ele --plot=relIso03 &
#python NMinus1Plots.py --channel=ele --plot=relIso04 &
#python NMinus1Plots.py --channel=ele --plot=mvaIdSpring15 &
#python NMinus1Plots.py --channel=ele --plot=jetPtRatiov1 &
#python NMinus1Plots.py --channel=ele --plot=jetPtRelv1 &
#python NMinus1Plots.py --channel=ele --plot=jetPtRelv2 &
#python NMinus1Plots.py --channel=ele --plot=jetPtRatiov2 &
#python NMinus1Plots.py --channel=ele --plot=jetBTagCSV &
#python NMinus1Plots.py --channel=ele --plot=jetDR &
python NMinus1Plots.py --channel=ele --plot=lostHits &
